version: '3'

services:
  ml-service:
    build:
      context: ./ml_service
      target: production
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=http://database:5002
      - REFERENCE_FACES_DIR=/app/reference_faces
    volumes:
      # Use the shared volume for reference faces
      - database-images:/app/reference_faces
    networks:
      - app-network
    depends_on:
      - database

  database:
    build:
      context: ./database
      target: runtime
    ports:
      - "5002:5002"
    volumes:
      # Volume for sharing images with ML service
      - database-images:/app/images
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      target: production
    ports:
      - "3000:3000"
    networks:
      - app-network

  # camera:
  #   build:
  #     context: ./camera
  #     target: runtime
  #   environment:
  #     - ML_SERVICE_URL=http://ml-service:5001/api/predict
  #     - STUDENT_DB_URL=http://database:5002/api/student
  #     - FRONTEND_UI_URL=http://frontend:3000/api/classroom/update
  #   depends_on:
  #     - ml-service
  #     - database
  #     - frontend
  #   networks:
  #     - app-network

volumes:
  database-images:

networks:
  app-network:
    driver: bridge